# Generated by Django 5.2.3 on 2025-06-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_invoice_remove_salesinvoiceitem_sales_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="dollar_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="inr_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="inr_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="conversion_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="dollar_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
