# Generated by Django 5.2.3 on 2025-06-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0004_invoiceentry_delete_invoice"),
        ("sales", "0004_invoice_dollar_total_invoice_inr_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceEntryConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumed_qty", models.PositiveIntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.invoice"
                    ),
                ),
                (
                    "invoice_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="retail.invoiceentry",
                    ),
                ),
            ],
        ),
    ]
