# Generated by Django 5.2.3 on 2025-06-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_invoiceentryconsumption_profit_absolute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="profit_selling_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
