# Generated by Django 5.2.3 on 2025-07-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_invoice_created_at_invoice_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="dnd_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
