# Generated by Django 6.0.1 on 2026-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_invoiceretailpartmap_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentryconsumption',
            name='consumed_qty',
            field=models.IntegerField(),
        ),
    ]
