# Generated by Django 6.0.1 on 2026-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_allow_negative_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartWiseTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(choices=[('customer_subtotal', 'Customer Subtotal'), ('invoice_detail', 'Invoice Detail'), ('part_grand_total', 'Part Grand Total')], max_length=20)),
                ('customer_code', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('part_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_date', models.CharField(blank=True, default='', max_length=20)),
                ('opening_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('opening_fc', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('opening_inr', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ccpl_to_wh_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ccpl_to_wh_fc', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('ccpl_to_wh_inr', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('wh_to_customer_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('wh_to_customer_fc', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('wh_to_customer_inr', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('closing_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('closing_fc', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('closing_inr', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_partwise_tracking',
                'indexes': [models.Index(fields=['part_number'], name='sales_partw_part_nu_c496d7_idx'), models.Index(fields=['customer_name'], name='sales_partw_custome_658866_idx'), models.Index(fields=['row_type'], name='sales_partw_row_typ_455df7_idx')],
            },
        ),
    ]
