# Generated by Django 6.0.1 on 2026-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_partwisetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='partwisetracking',
            name='invoice_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
