# Generated by Django 5.2.3 on 2025-06-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0003_invoice_remove_retailinvoiceitem_invoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                ("part_number", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("qty", models.PositiveIntegerField()),
                ("usd_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("usd_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("inr_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inr_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
