# Generated by Django 5.2.3 on 2025-07-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0007_invoiceentry_retail_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceentry",
            name="difference",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoiceentry",
            name="rate_sale_from_wh",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoiceentry",
            name="rate_sale_from_wh_per_unit",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoiceentry",
            name="surcharge",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
