# Generated by Django 5.2.3 on 2025-06-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                ("part_number", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("qty", models.PositiveIntegerField()),
                ("dollar_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="sales_invoice",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="salesinvoiceitem",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="SalesInvoice",
        ),
        migrations.DeleteModel(
            name="SalesInvoiceItem",
        ),
    ]
