# Generated by Django 5.2.3 on 2025-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_invoiceentryconsumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="profit_absolute",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="profit_fx_only",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="profit_fx_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="selling_price_inr",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
