# Generated by Django 5.2.3 on 2025-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_invoice_dnd_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="base_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="dnd_charges",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="fc_rate_with_discount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="fc_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceentryconsumption",
            name="taxable_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
