# Generated by Django 5.2.3 on 2025-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_invoiceentryconsumption_base_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="plant_code",
            field=models.CharField(default="1002", max_length=10),
        ),
    ]
