# Generated by Django 5.2.3 on 2025-07-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_invoiceretailpartmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_qty",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
