# Generated by Django 5.2.3 on 2025-08-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_invoiceentryconsumption_diff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="conversion_rate",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="dollar_rate",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="dollar_total",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="inr_rate",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="inr_total",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="base_value",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="diff",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="dnd_charges",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="fc_rate_with_discount",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="fc_value",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="profit_absolute",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="profit_fx_only",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="profit_fx_rate",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="rate_sale_from_wh",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="rate_sale_from_wh_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="selling_price_inr",
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="surcharge",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceentryconsumption",
            name="taxable_value",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
    ]
