# Generated by Django 6.0.1 on 2026-02-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_invoice_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceretailpartmap',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
