# Generated by Django 5.2.3 on 2025-06-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0004_invoiceentry_delete_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceentry",
            name="invoice_number",
        ),
    ]
