# Generated by Django 5.2.3 on 2025-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0006_invoiceentry_created_at_invoiceentry_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceentry",
            name="retail_invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
