# Generated by Django 5.2.3 on 2025-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0008_invoiceentry_difference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceentry",
            name="conversion_rate",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="difference",
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="inr_rate",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="inr_total",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="rate_sale_from_wh",
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="rate_sale_from_wh_per_unit",
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="surcharge",
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="usd_rate",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name="invoiceentry",
            name="usd_total",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
