# Generated by Django 6.0.1 on 2026-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_allow_negative_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentry',
            name='plating_charges',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoiceentry',
            name='plating_conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
